gettimeofday_test: gettimeofday_test.c
	gcc -o gettimeofday_test.out gettimeofday_test.c -Wall

measure_syscall: measure_syscall.c
	gcc -o measure_syscall.out measure_syscall.c -Wall

measure_context_switching: measure_context_switching.c
	gcc -o measure_context_switching.out measure_context_switching.c -Wall