p1: p1.c
	gcc -o p1.out p1.c -Wall

p2: p2.c
	gcc -o p2.out p2.c -Wall

p3: p3.c
	gcc -o p3.out p3.c -Wall

p4: p4.c
	gcc -o p4.out p4.c -Wall

p5: p5.c
	gcc -o p5.out p5.c -Wall

p6: p6.c
	gcc -o p6.out p6.c -Wall